### ISSUE TITLE
（已解决）是不是少了个包啊

### ISSUE THREAD

**Issue by XiaoMiku01** [Misaka17032/genshin-lyre-auto-play#1]
File "C:\Users\15619\Desktop\genshin-lyre-auto-play-main\genshin-lyre-auto-play-main\midi\messages\checks.py", line 4, in <module>
    from ..py2 import convert_py2_bytes
ModuleNotFoundError: No module named 'midi.py2'

**Comment by m0n3t4r** [comment]
我也怀疑给的依赖有问题
```
Traceback (most recent call last):
  File "E:\Python\genshin-lyre-auto-play-main\piano.py", line 5, in <module>
    from midi.midifiles.midifiles import MidiFile
  File "E:\Python\genshin-lyre-auto-play-main\midi\midifiles\__init__.py", line 1, in <module>
    from .meta import MetaMessage, UnknownMetaMessage, KeySignatureError
  File "E:\Python\genshin-lyre-auto-play-main\midi\midifiles\meta.py", line 18, in <module>
    from ..messages import BaseMessage, check_time
  File "E:\Python\genshin-lyre-auto-play-main\midi\messages\__init__.py", line 1, in <module>
    from .checks import check_time
  File "E:\Python\genshin-lyre-auto-play-main\midi\messages\checks.py", line 4, in <module>
    from ..py2 import convert_py2_bytes
ModuleNotFoundError: No module named 'midi.py2'``
```

**Comment by HimuraYuu** [comment]
同问

**Comment by XiaoMiku01** [comment]
解决了：
在midi文件夹下创建一个py2.py包
内容
`import sys

PY2 = (sys.version_info.major == 2)


def convert_py2_bytes(data):
    """Convert bytes object to bytearray in Python 2.
    Many parts of Mido such as ``Parser.feed()`` and
    ``Message.from_bytes()`` accept an iterable of integers.
    In Python 3 you can pass a byte string::
        >>> list(b'\x01\x02\x03')
        [1, 2, 3]
    while in Python 2 this happens::
        >>> list(b'\x01\x02\x03')
        ['\x01', '\x02', '\x03']
    This function patches over the difference::
        >>> list(convert_py2_bytes(b'\x01\x02\x03'))
        [1, 2, 3]
    """
    if PY2 and isinstance(data, bytes):
        return bytearray(data)
    else:
        return data`

**Comment by XiaoMiku01** [comment]
解决了：
在midi文件夹下创建一个py2.py包
内容：
import sys

PY2 = (sys.version_info.major == 2)

def convert_py2_bytes(data):
"""Convert bytes object to bytearray in Python 2.
Many parts of Mido such as Parser.feed() and
Message.from_bytes() accept an iterable of integers.
In Python 3 you can pass a byte string::
>>> list(b'\x01\x02\x03')
[1, 2, 3]
while in Python 2 this happens::
>>> list(b'\x01\x02\x03')
['\x01', '\x02', '\x03']
This function patches over the difference::
>>> list(convert_py2_bytes(b'\x01\x02\x03'))
[1, 2, 3]
"""
if PY2 and isinstance(data, bytes):
return bytearray(data)
else:
return data

**Comment by XiaoMiku01** [comment]
解决了：
在midi文件夹下创建一个py2.py包
内容
`import sys

PY2 = (sys.version_info.major == 2)

def convert_py2_bytes(data):
"""Convert bytes object to bytearray in Python 2.
Many parts of Mido such as Parser.feed() and
Message.from_bytes() accept an iterable of integers.
In Python 3 you can pass a byte string::
>>> list(b'\x01\x02\x03')
[1, 2, 3]
while in Python 2 this happens::
>>> list(b'\x01\x02\x03')
['\x01', '\x02', '\x03']
This function patches over the difference::
>>> list(convert_py2_bytes(b'\x01\x02\x03'))
[1, 2, 3]
"""
if PY2 and isinstance(data, bytes):
return bytearray(data)
else:
return data`

**Comment by XiaoMiku01** [comment]
解决了：
在midi文件夹下创建一个py2.py包
内容：
```python
import sys

PY2 = (sys.version_info.major == 2)


def convert_py2_bytes(data):
    """Convert bytes object to bytearray in Python 2.
    Many parts of Mido such as ``Parser.feed()`` and
    ``Message.from_bytes()`` accept an iterable of integers.
    In Python 3 you can pass a byte string::
        >>> list(b'\x01\x02\x03')
        [1, 2, 3]
    while in Python 2 this happens::
        >>> list(b'\x01\x02\x03')
        ['\x01', '\x02', '\x03']
    This function patches over the difference::
        >>> list(convert_py2_bytes(b'\x01\x02\x03'))
        [1, 2, 3]
    """
    if PY2 and isinstance(data, bytes):
        return bytearray(data)
    else:

        return data
```

**Comment by XiaoMiku01** [comment]
> 解决了：
> 在midi文件夹下创建一个py2.py文件
> 内容：
> 
> ```python
> import sys
> 
> PY2 = (sys.version_info.major == 2)
> 
> 
> def convert_py2_bytes(data):
>     """Convert bytes object to bytearray in Python 2.
>     Many parts of Mido such as ``Parser.feed()`` and
>     ``Message.from_bytes()`` accept an iterable of integers.
>     In Python 3 you can pass a byte string::
>         >>> list(b'\x01\x02\x03')
>         [1, 2, 3]
>     while in Python 2 this happens::
>         >>> list(b'\x01\x02\x03')
>         ['\x01', '\x02', '\x03']
>     This function patches over the difference::
>         >>> list(convert_py2_bytes(b'\x01\x02\x03'))
>         [1, 2, 3]
>     """
>     if PY2 and isinstance(data, bytes):
>         return bytearray(data)
>     else:
> 
>         return data
> ```

**Comment by HimuraYuu** [comment]
找到你的依赖了 一个叫mido的包

**Comment by Misaka17032** [comment]
已修复，之前忘上传了
