### ISSUE TITLE
Program crashes, shows [?]

### ISSUE THREAD

**Issue by m4xolotl** [Misaka17032/genshin-lyre-auto-play#10]
Picture; https://i.imgur.com/kL9BSAW.png

When I enter anything the program automatically closes

**Comment by Misaka17032** [comment]
Sorry for that, utf-8 characters are used.
Try to add `# -*- coding: utf-8 -*-` in each file.

**Comment by m4xolotl** [comment]
I have tried 👍 

https://i.imgur.com/8nhplnq.png

**Comment by Misaka17032** [comment]
There's no need to change `.mid` file, just change `piano.py`

**Comment by m4xolotl** [comment]
https://i.imgur.com/zaQMuOT.png

**Comment by m4xolotl** [comment]
https://i.imgur.com/6C2XSPM.png

**Comment by Misaka17032** [comment]
[try this one](https://github.com/Misaka17032/genshin-lyre-auto-play/files/6217400/piano.zip)

**Comment by m4xolotl** [comment]
https://i.imgur.com/7SluRtK.png

**Comment by Misaka17032** [comment]
input `cmajor` instead of `cmajor.mid`

**Comment by m4xolotl** [comment]
it works! but how to stop the program?

**Comment by Misaka17032** [comment]
Try to close the cmd window by tapping the "Windows key"
