### ISSUE TITLE
升降调时给不同音轨区分权重

### ISSUE THREAD

**Issue by articuno144** [Misaka17032/genshin-lyre-auto-play#11]
像https://www.midishow.com/en/midi/122907.html 这种谱子，和弦和主旋律跨了超过3个八度，怎么样都不太可能fit好。这时候一般好像觉得还原主旋律比较重要一点。
目前https://github.com/Misaka17032/genshin-lyre-auto-play/blob/377c808a3c563ed2bd55d5b947050eec4b9973d3/piano.py#L62 这里把所有音轨都融到一起了，好像丢失了每个音符对应的音轨信息，不太好实现权重区分。
还有个方向是用Hanning window过滤一下，我简单写了一个，但需要手动输入音域参数，好像不太好。

**Comment by Misaka17032** [comment]
融音轨的原因是有时候谱子是分左右手两个音轨，一般来说谱子是自定义的，所以可以避免多个叠加的情况
