### ISSUE TITLE
"Try to culculate play speed...... Failed. Make sure the fileis not broken or input custom speed:（7）"

### ISSUE THREAD

**Issue by m4xolotl** [Misaka17032/genshin-lyre-auto-play#13]
For all midis not included, it shows the same error (even re-exporting the included files will also cause the same error)

It shows "Try to culculate play speed......
Failed. Make sure the fileis not broken or input custom speed:（7）"

Putting a custom not 60 or 120 will immediately crash the program
Putting 60 will go to next step; https://i.imgur.com/rcZAtk9.png

But program still crahes after

**Comment by m4xolotl** [comment]
Example file link; https://drive.google.com/file/d/1TEQYkI3bXjob3FPmaO0VPAAZDet58TrX/view?usp=sharing

**Comment by Misaka17032** [comment]
The midi file is not in a standard format. Try this one:
[dota.zip](https://github.com/Misaka17032/genshin-lyre-auto-play/files/6217509/dota.zip)

**Comment by m4xolotl** [comment]
what program do you use to make standard format midis?

**Comment by Misaka17032** [comment]
All mainstream music editors are available.
