### ISSUE TITLE
通过musescore3直接导出的midi文件无法正常运作

### ISSUE THREAD

**Issue by Bubbleioa** [Misaka17032/genshin-lyre-auto-play#14]
> MS版本 3.6.2

问题描述：通过MS导出的midi文件在加载过后`mmax`变量为`0`，哪怕是单个音符。

解决手段：通过导入到其他软件（比如FL）再导出即可解决。

**Comment by AzusaTsang** [comment]
调试了下发现musescore导出来的最后的`info['type']`是`'end_of_track'`不在`type = ['note_on','note_off']`里

**Comment by Misaka17032** [comment]
有ms导出的midi文件样本吗？
我是以fl的格式为参照的，第二个音轨存tempo的那种。

**Comment by Bubbleioa** [comment]
> 有ms导出的midi文件样本吗？
> 我是以fl的格式为参照的，第二个音轨存tempo的那种。

https://1drv.ms/u/s!AiY5CF6SJ9HF2hA0cRfIcZu5c1Sj

**Comment by Misaka17032** [comment]
新版本已修复。
