### ISSUE TITLE
I found another version of canon in the website but I can't play it by your software. Can you resolve it?

### ISSUE THREAD

**Issue by wadx2019** [Misaka17032/genshin-lyre-auto-play#15]
Here is the URL https://www.midishow.com/midi/21749.html?s=509510.

**Comment by articuno144** [comment]
This is the same problem as #14 . After the loop https://github.com/Misaka17032/genshin-lyre-auto-play/blob/2ccd63d3fb6faeaa1f2d81ab0b33d6181dbe6355/piano.py#L95 , `end_track` is still an empty list. @Misaka17032 maybe consider adding a default note duration for each note like in https://github.com/articuno144/genshin-lyre-auto-play/blob/7eeda0ce0d7330a1077e164393a9428a37f27359/piano.py#L87.

**Comment by wadx2019** [comment]
So you mean your code just can deal with some specific mid file whose end_track is not empty?

**Comment by articuno144** [comment]
Exactly. We should fix this in the coming updates.

**Comment by wadx2019** [comment]
OK, looking forward to your better performance!

**Comment by Misaka17032** [comment]
Fixed in the new version.
