### ISSUE TITLE
English README

### ISSUE THREAD

**Issue by articuno144** [Misaka17032/genshin-lyre-auto-play#16]
ENGLISH PLEASE!

**Comment by yllhwa** [comment]
I am going to translate it to English today.

**Comment by Misaka17032** [comment]
New branch and in-text output translation, thanks!
(try to avoid using utf-8 characters)
（麻烦你了）

**Comment by jgyy** [comment]
threading.Thread(target=watch_dog,args=("原神",)).start()

The code should detect English genshin client also

**Comment by yllhwa** [comment]
> threading.Thread(target=watch_dog,args=("原神",)).start()
> 
> The code should detect English genshin client also

Yes, I'll pay attention to that.

**Comment by yllhwa** [comment]
pr at #19

**Comment by jgyy** [comment]
thanks for pull request, as for the songs list, do include all the English names also as my terminal cannot accept Chinese character inputs.
多谢了

**Comment by yllhwa** [comment]
> thanks for pull request, as for the songs list, do include all the English names also as my terminal cannot accept Chinese character inputs.
> 多谢了
maybe you can just change the file's name? XD

**Comment by jgyy** [comment]
i am doing that in the meantime haha. Still thanks for the repo

**Comment by yllhwa** [comment]
thx the owner, I just did some little things. :)
