### ISSUE TITLE
Program crashes after the timer runs out

### ISSUE THREAD

**Issue by Quenom** [Misaka17032/genshin-lyre-auto-play#18]
https://imgur.com/a/pxuq0TJ

piano.py from https://github.com/Misaka17032/genshin-lyre-auto-play/issues/10#issuecomment-808898876 works fine

latest(?) version that still works
https://github.com/Misaka17032/genshin-lyre-auto-play/blob/377c808a3c563ed2bd55d5b947050eec4b9973d3/piano.py

**Comment by yllhwa** [comment]
please replace ”原神” in the program with your game window's title.
I add a  feature to automaticly close the program once it's not in the front.

**Comment by Quenom** [comment]
That works, thanks
