### ISSUE TITLE
输入midi名后只运行一下

### ISSUE THREAD

**Issue by icyknife** [Misaka17032/genshin-lyre-auto-play#20]
管理员权限运行run.bat后，输入midi名只运行一下，然后关闭

**Comment by icyknife** [comment]
输入midi名，选择是否变调后，会切到游戏窗口，按键只输入了一次，程序就自动销毁了

**Comment by yllhwa** [comment]
将这行代码注释试试呢？
threading.Thread(target=watch_dog,args=("原神",)).start()

**Comment by icyknife** [comment]
已解决，感谢
