### ISSUE TITLE
按键谱导出

### ISSUE THREAD

**Issue by articuno144** [Misaka17032/genshin-lyre-auto-play#21]
虽然严格来说不允许用脚本弹，但对我们广大玩家来说还是有根据midi文件生成按键谱的需求的。

建议增加按键谱导出功能。

**Comment by Fuchange** [comment]
有个问题， 按键谱该如何表述“节奏”？如果有好的方法的话到处本身导师容易

**Comment by articuno144** [comment]
个人的几个想法：
1. 用空格长度做可视化
2. 直接写间隔时间的数字
3. 把是否有音符画在数轴上，做fft拟合小节，标拍子
