### ISSUE TITLE
有一些严重的bug

### ISSUE THREAD

**Issue by Looong01** [Misaka17032/genshin-lyre-auto-play#22]
我用的是visual studio 2019
运行第一次运行没有问题，再次点击运行就无法运行了，输入曲名、是否自动变调之后，直接切换到原神窗口，切回去之后发现显示press any key，不显示输入延时。也就是说，输入y/n之后，直接切到原神窗口，并且程序结束运行

**Comment by Looong01** [comment]
我怀疑是midi的问题

**Comment by yllhwa** [comment]
请注释掉
threading.Thread(target=watch_dog,args=("原神",)).start()
试试，可能是我的这个方法带来了问题

**Comment by yllhwa** [comment]
我猜测是获取的句柄是启动器的而不是原神窗口。晚些时候我尝试修复，发个新的pull request

**Comment by Looong01** [comment]
注释之后确实没问题了，但是同时那个延时机制也没有了

**Comment by Misaka17032** [comment]
试试新版本

**Comment by Looong01** [comment]
嗯嗯没问题了，倒是想请教一下，midi的调音的目的和原理是什么呢？

**Comment by Misaka17032** [comment]
midi本质就是“电子乐谱”，存储的是音符的时间、音高、音量等信息。
