### ISSUE TITLE
What is playback speed?

### ISSUE THREAD

**Issue by ZhaanCS** [Misaka17032/genshin-lyre-auto-play#23]
If I put in the bpm it was too fast (155), I have no clue if it's even supposed to be bpm

^^^ The version earlier today ^^^

---

vvv current version vvv

It finds the song speed but its REALLY slow, what do I need to change in the song file to make the default speed faster

[Incomplete night of nights I threw together (1 minute)](https://github.com/ZhaanCS/upload/blob/main/nightofnight.mid?raw=true)

**Comment by Misaka17032** [comment]
Should try to input bpm / 20.

**Comment by Misaka17032** [comment]
And also try with this file:
[nightofnight.zip](https://github.com/Misaka17032/genshin-lyre-auto-play/files/6222030/nightofnight.zip)

**Comment by ZhaanCS** [comment]
I tried 155/20 (~8) at first, but I had to do like 26 for it to sound decent

**Comment by ZhaanCS** [comment]
> And also try with this file:
> [nightofnight.zip](https://github.com/Misaka17032/genshin-lyre-auto-play/files/6222030/nightofnight.zip)

this worked, what did you change in the file?

**Comment by Misaka17032** [comment]
I just re-exported with FL Studio. I'm trying to figure out what happened with the original file.

**Comment by ZhaanCS** [comment]
I guess I'll go redownload fl studio (or maybe reason suite would work? ill test it out) 

I used https://onlinesequencer.net since I didn't have any music software installed on this computer

**Comment by Misaka17032** [comment]
It seems like there's some problem with the time of each note in that midi file generated with the website. Didn't find any bug in the code.
Btw, that sounds nice.
~~**Liked by Sakuya**~~
