### ISSUE TITLE
新载入的mid音乐显得较慢

### ISSUE THREAD

**Issue by icyknife** [Misaka17032/genshin-lyre-auto-play#24]
新载入的mid音乐显得较慢，请问有解决方案吗

**Comment by Misaka17032** [comment]
是比起源文件显得慢了吗？
总之，尝试拉高文件的bpm。

**Comment by icyknife** [comment]
已解决，thx : )

**Comment by icyknife** [comment]
> > 已解决，thx : )
> 
> 可以请问下是怎么解决的吗 👍

抱歉现在才看到，把midi文件放入MidiEditor软件中更改bpm，修改bpm的具体教程可以百度或者谷歌（其实挺简单的，找到位置修改数值就行，尽量改高一点）
