### ISSUE TITLE
_en 英文文件

### ISSUE THREAD

**Issue by Fuchange** [Misaka17032/genshin-lyre-auto-play#27]
_en 文件是为了输出英文文本内容？ 不如换成 .ini 格式 的翻译文件？ 

稍后如果我有时间的话可以提供pr

**Comment by yllhwa** [comment]
我为了最小限度的改变作者的代码就直接翻译了(

**Comment by Fuchange** [comment]
> 我为了最小限度的改变作者的代码就直接翻译了(

那看来需要作者决断了 @Misaka17032

**Comment by articuno144** [comment]
项目的About也可以加上英文，现在搜索界面只能看到中文小字，容易劝退国际友人。

**Comment by Misaka17032** [comment]
直接挂了个English的分支
