### ISSUE TITLE
按拍输出键位

### ISSUE THREAD

**Issue by Fuchange** [Misaka17032/genshin-lyre-auto-play#28]
受 #21  的启发， 如果能将程序模拟按键改为 按拍输出对应按键 是不是在符合 官方利益的同时 帮助玩家玩乐器？

具体 输出 方式有待讨论，例如其他因有一般的下落式，或者字符界面闪烁按键？

**Comment by yllhwa** [comment]
不太懂乐理，不过MIDI容易分出小节吗？

**Comment by Fuchange** [comment]
> 不太懂乐理，不过MIDI容易分出小节吗？

不需要大改，在现有基础上将模拟按键的 win32api.keybd_event 替换为输出相关的函数按说就可以了

**Comment by articuno144** [comment]
不切到原神窗口，切个记事本是不是就是这种效果？

**Comment by Misaka17032** [comment]
大概先写了一个简易版的，有改进可以提prw
