### ISSUE TITLE
Re：

### ISSUE THREAD

**Issue by Conchorbor** [Misaka17032/genshin-lyre-auto-play#36]
如果不是音域超了的问题 为啥这个mid一开就闪退 mid文件有更具体的要求吗
[Snow halation.zip](https://github.com/Misaka17032/genshin-lyre-auto-play/files/6289146/Snow.halation.zip)

**Comment by Misaka17032** [comment]
我觉得是文件的问题，我试图用fl打开，但是失败了。你是用的什么软件？

**Comment by Conchorbor** [comment]
midieditor和WindowsMediaPlayer能打开

**Comment by Misaka17032** [comment]
因为之前用fl一打开就卡死，重新分析了一下，发现是文件过长，如下图：![](https://z3.ax1x.com/2021/08/23/h9CNQS.png)
一般来说，遇到这种问题是因为文件末尾的若干音符标记的时间尺度过大，删去那些音符即可。
