### ISSUE TITLE
解码复杂的midi文件

### ISSUE THREAD

**Issue by articuno144** [Misaka17032/genshin-lyre-auto-play#4]
很多下载下来的midi歌曲由于下列原因无法很好地直接表演：
1. 音域太高或太低
2. 有太多黑键音

不知道是否可以通过识别音域，以及穷举尝试自动变调（共12种情况）来支持更多的midi歌曲。我打算试一下，可行的话我交一个PR。

**Comment by loyamaqu** [comment]
不懂乐理，猜测意思是游戏里面的21个音调太少了？那除非别的音调能够通过这些现有音调混合来实现，不然就要动游戏客户端了吧，这不太现实。

**Comment by articuno144** [comment]
已经实现了哈，详见PR #6

**Comment by Misaka17032** [comment]
草，忘记了，这就同意

**Comment by articuno144** [comment]
> 草，忘记了，这就同意

不知道你测试了没哈哈哈，推荐用https://www.midishow.com/en/midi/bgm-midi-download-123647 这种测试一下哈
