### ISSUE TITLE
希望大佬能修改一下hand文件的空格键位

### ISSUE THREAD

**Issue by iYukim** [Misaka17032/genshin-lyre-auto-play#41]
hand文件控制弹琴间隔的键位空格和游戏跳跃键位冲突，希望能改成不影响游戏的

**Comment by iYukim** [comment]
这样就可以不关闭程序也能继续游戏了

**Comment by Misaka17032** [comment]
改一下128和130行的win32con.VK_SPACE就可以了。

**Comment by iYukim** [comment]
可大佬问题就是我是纯萌新阿完全不懂这方面

**Comment by Misaka17032** [comment]
你想改成什么键？

**Comment by iYukim** [comment]
就是机械键盘的大写0键可以嘛，会不会有什么冲突

**Comment by iYukim** [comment]
改成机械键盘的大写0键位可以嘛，会不会有问题

**Comment by iYukim** [comment]
改成机械建盘的大写0键位可以嘛，应该不会有冲突吧

**Comment by Misaka17032** [comment]
数字小键盘的0？

**Comment by iYukim** [comment]
就是机械键盘右边的的九宫格样式的大写数字键位0

**Comment by iYukim** [comment]
和P键上面的0应该不会冲突吧

**Comment by Misaka17032** [comment]
下载[这个](https://github.com/Misaka17032/genshin-lyre-auto-play/releases/download/V1.1/hand.zip)就行。

**Comment by iYukim** [comment]
谢谢大佬！

**Comment by Misaka17032** [comment]
没事。可以稍等一小会儿，我会上传hand的功能更新

**Comment by Misaka17032** [comment]
> 没事。可以稍等一小会儿，我会上传hand的功能更新

参见[此处](https://github.com/Misaka17032/genshin-lyre-auto-play/releases/tag/V1.2)

**Comment by iYukim** [comment]
关于v1.2的使用最新提议：使用hand模式时可以不用让mask置顶，同v1.1一样窗口即可，mask置不置顶对演奏并无大影响,置顶后在特殊情况下会遮挡游戏界面(少数情况如开启角色界面)

**Comment by iYukim** [comment]
大佬纯免费开发我都想捐款了有无群聊

**Comment by iYukim** [comment]
新发现问题：v1.2 hand在后台运行时会对游戏流畅度有一定影响(不定时卡顿一次)

**Comment by iYukim** [comment]
v1.1并无该情况

**Comment by iYukim** [comment]
当然我也不能确定是不是我的电脑问题，但这个情况已经存在半天了hhhhh

**Comment by Misaka17032** [comment]
[现在版本](https://github.com/Misaka17032/genshin-lyre-auto-play/releases/tag/V1.2.1)可以按小键盘数字1来开关mask窗口（留着的主要原因是因为全屏模式）
关于资源占用问题，在本机上我并没有发现问题（不移动游戏窗口时保持在0.5%以下），你可以试试使用时用任务管理器查看资源占用。

**Comment by iYukim** [comment]
资源占用方面无问题下午的时候就确认了,现在卡顿次数少了，可能是我机器的原因，明后天换个机器试验
