### ISSUE TITLE
执行build.py后输入曲号后会自动关闭

### ISSUE THREAD

**Issue by RhapGS** [Misaka17032/genshin-lyre-auto-play#42]
运行build.py后，输入midi名只运行一下，然后关闭
救教

**Comment by Misaka17032** [comment]
这种情况是文件运行中错误导致的；请检查一下使用python命令运行时是否有问题，并且确保编译出的exe在正确的路径（即同目录下有名为songs的文件夹）

**Comment by Misaka17032** [comment]
下载本项目配置好环境后按[这里](https://github.com/Misaka17032/genshin-lyre-auto-play#%E6%96%B9%E6%B3%95%E4%BA%8C)运行
