### ISSUE TITLE
去哪里可以下载别的mid文件呀

### ISSUE THREAD

**Issue by pooneyy** [Misaka17032/genshin-lyre-auto-play#43]

**Comment by pooneyy** [comment]
比如可莉pv的音乐

**Comment by sertwen** [comment]
我用的这个网站，需要注册 [https://www.midishow.com/](https://www.midishow.com/)

**Comment by pooneyy** [comment]
> 我用的这个网站，需要注册 https://www.midishow.com/

我发现网上下载的，很多超出了支持的音域，或者有黑键。我现在自制mid了
