### ISSUE TITLE
【输出有问题】神女劈观.mid

### ISSUE THREAD

**Issue by emako** [Misaka17032/genshin-lyre-auto-play#44]
[神女劈観.zip](https://github.com/Misaka17032/genshin-lyre-auto-play/files/7920502/default.zip)
还没看太懂mid格式，不知道哪里解析有问题？

**Comment by Misaka17032** [comment]
检查了一下，似乎是播放速度的问题。请尝试一下[这个文件](https://github.com/Misaka17032/genshin-lyre-auto-play/files/7922110/default.zip)，应该能够成功运行
