### ISSUE TITLE
同個音不能連按

### ISSUE THREAD

**Issue by han-han030** [Misaka17032/genshin-lyre-auto-play#45]
請問是我mid檔的問題嗎?
[命に嫌われている。 (2)](https://drive.google.com/file/d/1dNE-2Oyyj6LdgHFfu0zxapbfRjiVbJKM/view?usp=sharing)

**Comment by Misaka17032** [comment]
测试了一下，可能真的是midi的问题。可以试一试[这个文件](https://github.com/Misaka17032/genshin-lyre-auto-play/files/7970594/default.zip)

**Comment by han-han030** [comment]
那我該怎麼修改這個midi

**Comment by Misaka17032** [comment]
请问你指的是对里面的音符进行修改吗？
