### ISSUE TITLE
输出自动低8度丢音

### ISSUE THREAD

**Issue by RhapGS** [Misaka17032/genshin-lyre-auto-play#46]
[https://www.dropbox.com/s/gq5e0cjnbluvivs/%E7%A5%9E%E5%A5%B3%E5%8A%88%E8%A7%80.mid?dl=0](url)
MIDI里的音符明明都在原神那三个8度的白键位，输出却莫名低了一个8度和丢音

**Comment by Misaka17032** [comment]
你好，经检查后发现此文件当中的三个八度低于脚本要求的三个八度，需要将所有音符升高一个八度。
