### ISSUE TITLE
沉睡后直接播放结束

### ISSUE THREAD

**Issue by hanuxxx** [Misaka17032/genshin-lyre-auto-play#5]
测试的卡农正常，自己找的midi出现了这种情况，甚至用fl限制音调范围再导出还是这样

**Comment by Misaka17032** [comment]
有midi文件样本吗？

**Comment by hanuxxx** [comment]
[http://d0.ananas.chaoxing.com/download/68355a8ae9333096dba854c2f0b3e261?at_=1616932012184&ak_=abd0fd0cfc6c790d33408b1a1a018492&ad_=dd36b35f058d8112a6eaeb28dfef9026&fn=white.mid](url)

**Comment by Misaka17032** [comment]
[试试这个](https://github.com/Misaka17032/genshin-lyre-auto-play/files/6217249/1.zip)

**Comment by hanuxxx** [comment]
你的这个可以播放了，为什么呢

**Comment by Misaka17032** [comment]
fl重写了一下tempo（bpm）的event
